#include "cmake.h"

#include <stdio.h>
#include <string.h>
#include <sys/stat.h>

#include "craft_toml.h"
#include "utils.h"
#include "platform.h"

int cmake_needs_regeneration(const char* project_root) {
    char cmake_path[PATH_SIZE];
    char toml_path[PATH_SIZE];
    snprintf(cmake_path, sizeof(cmake_path), "%s/CMakeLists.txt", project_root);
    snprintf(toml_path, sizeof(toml_path), "%s/craft.toml", project_root);

    struct stat cmake_stat;
    struct stat toml_stat;

    if (stat(cmake_path, &cmake_stat) != 0) return 1;
    if (stat(toml_path, &toml_stat) != 0) return 0;

    return toml_stat.st_mtime > cmake_stat.st_mtime;
}

// Writes the header, cmake_minimum_required, project, and standards
static void write_header(FILE* file, project_config_t* config) {
    fprintf(file, "# This file is automatically generated by Craft.\n");
    fprintf(file, "# Do not edit manually, changes will be overwritten.\n");
    fprintf(file, "# For additional custom CMake use CMakeLists.extra.cmake instead.\n\n");

    fprintf(file, "cmake_minimum_required(VERSION 3.14)\n");
    fprintf(file, "project(\"%s\")\n\n", config->project.name);

    if (config->project.has_c_standard) {
        fprintf(file, "set(CMAKE_C_STANDARD %d)\n", config->project.c_standard);
    }
    if (config->project.has_cpp_standard) {
        fprintf(file, "set(CMAKE_CXX_STANDARD %d)\n", config->project.cpp_standard);
    }
    fprintf(file, "\n");
}

// Writes the GLOB_RECURSE sources
static void write_sources(FILE* file, project_config_t* config) {
    const char* extension = strcmp(config->project.language, "c") == 0 ? "*.c" : "*.cpp";

    fprintf(file, "file(GLOB_RECURSE SOURCES");

    if (config->build.source_dir_count > 0) {
        for (int i = 0; i < config->build.source_dir_count; i++) {
            fprintf(file, " \"%s/%s\"", config->build.source_dirs[i], extension);
        }
    }
    else {
        fprintf(file, " \"src/%s\"", extension);
    }

    fprintf(file, ")\n\n");

    // Also pick up source files in root directory
    fprintf(file, "file(GLOB ROOT_SOURCES \"./%s\")\n", extension);
    fprintf(file, "list(APPEND SOURCES ${ROOT_SOURCES})\n\n");
}

// Writes the add_executable or add_library target
static void write_target(FILE* file, project_config_t* config) {
    if (strcmp(config->build.type, "executable") == 0) {
        fprintf(file, "add_executable(%s ${SOURCES})\n\n", config->project.name);
    }
    else if (strcmp(config->build.type, "static-library") == 0) {
        fprintf(file, "add_library(%s STATIC ${SOURCES})\n\n", config->project.name);
    }
    else if (strcmp(config->build.type, "shared-library") == 0) {
        fprintf(file, "add_library(%s SHARED ${SOURCES})\n\n", config->project.name);
    }
    else if (strcmp(config->build.type, "header-only") == 0) {
        fprintf(file, "add_library(%s INTERFACE)\n\n", config->project.name);
    }
}

// Writes target_include_directories for the project itself
static void write_includes(FILE* file, project_config_t* config) {
    const char* visibility = strcmp(config->build.type, "header-only") == 0 ? "INTERFACE" : "PRIVATE";

    fprintf(file, "target_include_directories(%s %s .", config->project.name, visibility);

    if (config->build.include_dir_count > 0) {
        for (int i = 0; i < config->build.include_dir_count; i++) {
            fprintf(file, " %s", config->build.include_dirs[i]);
        }
    }
    else {
        fprintf(file, " include");
    }

    fprintf(file, ")\n\n");
}

// Writes target_link_directories and target_link_libraries for manual libs
static void write_libs(FILE* file, project_config_t* config) {
    if (config->build.lib_dir_count > 0) {
        fprintf(file, "target_link_directories(%s PRIVATE .", config->project.name);
        for (int i = 0; i < config->build.lib_dir_count; i++) {
            fprintf(file, " ${CMAKE_CURRENT_SOURCE_DIR}/%s", config->build.lib_dirs[i]);
        }
        fprintf(file, ")\n\n");
    }

    if (config->build.lib_count > 0) {
        fprintf(file, "target_link_libraries(%s PRIVATE", config->project.name);
        for (int i = 0; i < config->build.lib_count; i++) {
            fprintf(file, " %s", config->build.libs[i]);
        }
        fprintf(file, ")\n\n");
    }
}

// Writes cmake for all defined build profiles
static void write_build_profiles(FILE* file, project_config_t* config) {
    for (int i = 0; i < config->profile_count; i++) {
        build_profile_t* profile = &config->profiles[i];

        fprintf(file, "if(CRAFT_PROFILE STREQUAL \"%s\")\n", profile->name);

        // Compiler flags
        fprintf(file, "\tif(MSVC)\n");
        fprintf(file, "\t\ttarget_compile_options(%s PRIVATE", config->project.name);
        if (profile->optimize) {
            fprintf(file, " /O2");
        }
        if (profile->symbols) {
            fprintf(file, " /Zi");
        }
        if (profile->warnings) {
            fprintf(file, " /W4");
        }
        if (profile->werror) {
            fprintf(file, " /WX");
        }
        fprintf(file, ")\n");
        fprintf(file, "\telse()\n");
        fprintf(file, "\t\ttarget_compile_options(%s PRIVATE", config->project.name);
        if (profile->optimize) {
            fprintf(file, " -O2");
        }
        if (profile->symbols) {
            fprintf(file, " -g");
        }
        if (profile->warnings) {
            fprintf(file, " -Wall -Wextra");
        }
        if (profile->werror) {
            fprintf(file, " -Werror");
        }
        if (profile->lto) {
            fprintf(file, " -flto");
        }
        fprintf(file, ")\n");
        fprintf(file, "\tendif()\n\n");

        // Custom defines
        if (profile->define_count > 0) {
            fprintf(file, "\ttarget_compile_definitions(%s PRIVATE", config->project.name);
            for (int j = 0; j < profile->define_count; j++) {
                fprintf(file, " %s", profile->defines[j]);
            }
            fprintf(file, ")\n\n");
        }

        // Custom flags
        if (profile->flag_count > 0) {
            fprintf(file, "\ttarget_compile_options(%s PRIVATE", config->project.name);
            for (int j = 0; j < profile->flag_count; j++) {
                fprintf(file, " %s", profile->flags[j]);
            }
            fprintf(file, ")\n\n");
        }

        // Custom link flags
        if (profile->link_flag_count > 0) {
            fprintf(file, "\ttarget_link_options(%s PRIVATE", config->project.name);
            for (int j = 0; j < profile->link_flag_count; j++) {
                fprintf(file, " %s", profile->link_flags[j]);
            }
            fprintf(file, ")\n\n");
        }

        // Sanitizers
        if (profile->sanitizer_count > 0) {
            fprintf(file, "\tif(NOT MSVC)\n");
            fprintf(file, "\t\ttarget_compile_options(%s PRIVATE", config->project.name);
            for (int i = 0; i < profile->sanitizer_count; i++)
                fprintf(file, " -fsanitize=%s", profile->sanitizers[i]);
            fprintf(file, ")\n");
            fprintf(file, "\t\ttarget_link_options(%s PRIVATE", config->project.name);
            for (int i = 0; i < profile->sanitizer_count; i++)
                fprintf(file, " -fsanitize=%s", profile->sanitizers[i]);
            fprintf(file, ")\n");
            fprintf(file, "\tendif()\n\n");
        }

        fprintf(file, "endif()\n\n");
    }
}

// Writes cmake to embed VERSION macro into binary
static int write_version_compile_definition(FILE* file, project_config_t* config) {
    fprintf(file, "set(VERSION %s)\n", config->project.version);
    fprintf(file, "target_compile_definitions(%s PRIVATE VERSION=\"${VERSION}\")\n\n", config->project.name);
    return 0;
}

// Writes cmake for a local path dependency (must be a Craft project)
static int write_path_dependency(FILE* file, const char* project_path, project_config_t* config, dependency_t* dep) {
    char dep_root[PATH_SIZE];
    snprintf(dep_root, sizeof(dep_root), "%s/%s", project_path, dep->value);

    project_config_t dep_config;
    if (load_project_config(&dep_config, dep_root) != 0) {
        fprintf(stderr, "Error: Could not load craft.toml for dependency '%s'\n", dep->name);
        return -1;
    }

    fprintf(file, "# %s\n", dep->name);
    fprintf(file, "if(NOT TARGET %s)\n", dep->name);
    fprintf(file, "    add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/%s ${CMAKE_BINARY_DIR}/%s)\n", dep->value, dep->name);
    fprintf(file, "endif()\n");
    fprintf(file, "target_link_libraries(%s PRIVATE %s)\n", config->project.name, dep->name);

    if (dep_config.build.include_dir_count > 0) {
        fprintf(file, "target_include_directories(%s PRIVATE", config->project.name);
        for (int j = 0; j < dep_config.build.include_dir_count; j++) {
            fprintf(file, " %s/%s", dep->value, dep_config.build.include_dirs[j]);
        }
        fprintf(file, ")\n");
    }
    else {
        fprintf(file, "target_include_directories(%s PRIVATE %s/include)\n", config->project.name, dep->value);
    }

    fprintf(file, "\n");
    return 0;
}

// Writes cmake for a git dependency
// If it is a Craft project use add_subdirectory
// If it has a CMakeLists.txt use add_subdirectory with user provided links
// Otherwise warn the user to configure it manually
static int write_git_dependency(FILE* file, const char* project_path, project_config_t* config, dependency_t* dep) {
    char dep_root[PATH_SIZE];
    snprintf(dep_root, sizeof(dep_root), "%s/.craft/deps/%s", project_path, dep->name);

    char dep_cmake[PATH_SIZE];
    snprintf(dep_cmake, sizeof(dep_cmake), "%s/CMakeLists.txt", dep_root);

    fprintf(file, "# %s\n", dep->name);

    // Best case, it's a Craft project, we know everything
    if (is_craft_project(dep_root)) {
        project_config_t dep_config;
        if (load_project_config(&dep_config, dep_root) != 0) {
            fprintf(stderr, "Error: Could not load craft.toml for dependency '%s'\n", dep->name);
            return -1;
        }

        fprintf(file, "if(NOT TARGET %s)\n", dep->name);
        fprintf(file, "    add_subdirectory(${CMAKE_SOURCE_DIR}/.craft/deps/%s ${CMAKE_SOURCE_DIR}/.craft/deps/%s/build)\n", dep->name, dep->name);
        fprintf(file, "endif()\n");
        fprintf(file, "target_link_libraries(%s PRIVATE %s)\n", config->project.name, dep->name);

        if (dep_config.build.include_dir_count > 0) {
            fprintf(file, "target_include_directories(%s PRIVATE", config->project.name);
            for (int j = 0; j < dep_config.build.include_dir_count; j++) {
                fprintf(file, " .craft/deps/%s/%s", dep->name, dep_config.build.include_dirs[j]);
            }
            fprintf(file, ")\n");
        }
        else {
            fprintf(file, "target_include_directories(%s PRIVATE .craft/deps/%s/include)\n", config->project.name, dep->name);
        }
    }

    // Has CMakeLists.txt but not a Craft project
    // Use add_subdirectory with user provided links
    else if (file_exists(dep_cmake)) {
        if (dep->links_count > 0) {
            fprintf(file, "if(NOT TARGET %s)\n", dep->links[0]);
        }
        else {
            fprintf(file, "if(NOT TARGET %s)\n", dep->name);
        }
        fprintf(file, "    add_subdirectory(${CMAKE_SOURCE_DIR}/.craft/deps/%s ${CMAKE_SOURCE_DIR}/.craft/deps/%s/build)\n", dep->name, dep->name);
        fprintf(file, "endif()\n");

        if (dep->links_count > 0) {
            fprintf(file, "target_link_libraries(%s PRIVATE", config->project.name);
            for (int j = 0; j < dep->links_count; j++) {
                fprintf(file, " %s", dep->links[j]);
            }
            fprintf(file, ")\n");
        }
        else {
            fprintf(stderr, "\nWarning: dependency '%s' has no link targets specified\n", dep->name);
            fprintf(stderr, "         Add --links when running craft add, or configure manually in craft.toml\n\n");
        }

        fprintf(file, "target_include_directories(%s PRIVATE .craft/deps/%s/include)\n", config->project.name, dep->name);
    }

    // No CMakeLists.txt - warn the user
    else {
        fprintf(stderr, "Warning: dependency '%s' does not appear to use CMake\n", dep->name);
        fprintf(stderr, "         Configure it manually in CMakeLists.extra.cmake\n");
    }

    fprintf(file, "\n");
    return 0;
}

// Writes the dependencies section with all dependencies using the previous helper functions
static int write_dependencies(FILE* file, const char* project_path, project_config_t* config) {

    // Only write if there are dependencies present
    if (config->dependencies.dependencies_count > 0) {
        fprintf(file, "# Dependencies\n");
        for (int i = 0; i < config->dependencies.dependencies_count; i++) {
            dependency_t* dep = &config->dependencies.dependencies[i];

            // Local path dependency to another craft project
            if (dep->type == DEP_PATH) {
                if (write_path_dependency(file, project_path, config, dep) != 0) {
                    fclose(file);
                    return -1;
                }
            }

            // Github external dependency
            else if (dep->type == DEP_GIT) {
                if (write_git_dependency(file, project_path, config, dep) != 0) {
                    fclose(file);
                    return -1;
                }
            }
        }
    }

    return 0;
}

// Writes the before escape hatch include
static void write_before_escape_hatch(FILE* file) {
    fprintf(file, "# Additional configuration in CMakeLists.before.cmake will go here\n");
    fprintf(file, "if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/CMakeLists.before.cmake)\n");
    fprintf(file, "    include(${CMAKE_CURRENT_SOURCE_DIR}/CMakeLists.before.cmake)\n");
    fprintf(file, "endif()\n\n");
}

// Writes the after escape hatch include
static void write_after_escape_hatch(FILE* file) {
    fprintf(file, "# Additional configuration in CMakeLists.after.cmake will go here\n");
    fprintf(file, "if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/CMakeLists.after.cmake)\n");
    fprintf(file, "    include(${CMAKE_CURRENT_SOURCE_DIR}/CMakeLists.after.cmake)\n");
    fprintf(file, "endif()\n");
}

int generate_project_cmake(const char* project_path, project_config_t* config) {
    char cmake_path[PATH_SIZE];
    snprintf(cmake_path, sizeof(cmake_path), "%s/CMakeLists.txt", project_path);

    FILE* file = fopen(cmake_path, "w");
    if (!file) {
        fprintf(stderr, "Error: Failed to create CMakeLists.txt\n");
        return -1;
    }

    write_header(file, config);
    write_before_escape_hatch(file);
    write_sources(file, config);
    write_target(file, config);
    write_includes(file, config);
    write_libs(file, config);
    write_build_profiles(file, config);
    write_version_compile_definition(file, config);
    write_dependencies(file, project_path, config);
    write_after_escape_hatch(file);

    fclose(file);
    return 0;
}

int generate_workspace_cmake(const char* workspace_root, workspace_config_t* config) {

    // Open CMakeLists.txt for writing
    char cmake_path[PATH_SIZE];
    snprintf(cmake_path, sizeof(cmake_path), "%s/CMakeLists.txt", workspace_root);

    FILE* file = fopen(cmake_path, "w");
    if (!file) {
        fprintf(stderr, "Error: Failed to create CMakeLists.txt\n");
        return -1;
    }

    // Write contents
    fprintf(file, "# This file is automatically generated by Craft.\n");
    fprintf(file, "# Do not edit manually, changes will be overwritten.\n");
    fprintf(file, "# For additional custom CMake use CMakeLists.extra.cmake instead.\n\n");

    fprintf(file, "cmake_minimum_required(VERSION 3.14)\n");
    fprintf(file, "project(craft_workspace)\n\n");

    write_before_escape_hatch(file);

    fprintf(file, "# Members\n");
    for (int i = 0; i < config->member_count; i++) {
        char member_path[PATH_SIZE];
        snprintf(member_path, sizeof(member_path), "%s/%s", workspace_root, config->members[i]);

        // Load member config and regenerate CMake if needed
        project_config_t member_config = {0};
        if (load_project_config(&member_config, member_path) != 0) {
            return -1;
        }
        if (validate_project_config(&member_config) != 0) {
            return -1;
        }
        if (cmake_needs_regeneration(member_path)) {
            generate_project_cmake(member_path, &member_config);
        }

        // Add member project as a subdirectory of the build
        fprintf(file, "if(NOT TARGET %s)\n", member_config.project.name);
        fprintf(file, "    add_subdirectory(${CMAKE_SOURCE_DIR}/%s ${CMAKE_BINARY_DIR}/%s)\n", config->members[i], config->members[i]);
        fprintf(file, "endif()\n\n");
    }

    write_after_escape_hatch(file);
    fclose(file);

    return 0;
}

int backup_cmake(const char* project_path) {
    char cmake_path[PATH_SIZE];
    snprintf(cmake_path, sizeof(cmake_path), "%s/CMakeLists.txt", project_path);

    char backup_path[PATH_SIZE];
    snprintf(backup_path, sizeof(backup_path), "%s/CMakeLists.backup.cmake", project_path);

    if (file_exists(cmake_path)) {
        copy_file(cmake_path, backup_path);
        return 1;
    }

    return 0;
}