#include "cmake.h"
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include "config.h"
#include "utils.h"
#include "platform.h"

int cmake_needs_regeneration(const char* project_root) {
    char cmake_path[1024];
    char toml_path[1024];
    snprintf(cmake_path, sizeof(cmake_path), "%s/CMakeLists.txt", project_root);
    snprintf(toml_path, sizeof(toml_path), "%s/craft.toml", project_root);

    struct stat cmake_stat;
    struct stat toml_stat;

    if (stat(cmake_path, &cmake_stat) != 0) return 1;
    if (stat(toml_path, &toml_stat) != 0) return 0;

    return toml_stat.st_mtime > cmake_stat.st_mtime;
}

// Writes the header, cmake_minimum_required, project, and standards
static void write_header(FILE* file, project_config_t* config) {
    fprintf(file, "# This file is automatically generated by Craft.\n");
    fprintf(file, "# Do not edit manually, changes will be overwritten.\n");
    fprintf(file, "# For additional custom CMake use CMakeLists.extra.cmake instead.\n\n");

    fprintf(file, "cmake_minimum_required(VERSION 3.14)\n");
    fprintf(file, "project(%s)\n\n", config->name);

    if (config->has_c_standard) {
        fprintf(file, "set(CMAKE_C_STANDARD %d)\n", config->c_standard);
    }
    if (config->has_cpp_standard) {
        fprintf(file, "set(CMAKE_CXX_STANDARD %d)\n", config->cpp_standard);
    }
    fprintf(file, "\n");
}

// Writes the GLOB_RECURSE sources
static void write_sources(FILE* file, project_config_t* config) {
    const char* extension = strcmp(config->language, "c") == 0 ? "*.c" : "*.cpp";

    fprintf(file, "file(GLOB_RECURSE SOURCES");

    if (config->source_dir_count > 0) {
        for (int i = 0; i < config->source_dir_count; i++) {
            fprintf(file, " \"%s/%s\"", config->source_dirs[i], extension);
        }
    }
    else {
        fprintf(file, " \"src/%s\"", extension);
    }

    fprintf(file, ")\n\n");
}

// Writes the add_executable or add_library target
static void write_target(FILE* file, project_config_t* config) {
    if (strcmp(config->build_type, "executable") == 0) {
        fprintf(file, "add_executable(%s ${SOURCES})\n\n", config->name);
    }
    else if (strcmp(config->build_type, "static-library") == 0) {
        fprintf(file, "add_library(%s STATIC ${SOURCES})\n\n", config->name);
    }
    else if (strcmp(config->build_type, "shared-library") == 0) {
        fprintf(file, "add_library(%s SHARED ${SOURCES})\n\n", config->name);
    }
    else if (strcmp(config->build_type, "header-only") == 0) {
        fprintf(file, "add_library(%s INTERFACE)\n\n", config->name);
    }
}

// Writes target_include_directories for the project itself
static void write_includes(FILE* file, project_config_t* config) {
    const char* visibility = strcmp(config->build_type, "header-only") == 0 ? "INTERFACE" : "PRIVATE";

    fprintf(file, "target_include_directories(%s %s", config->name, visibility);

    if (config->include_dir_count > 0) {
        for (int i = 0; i < config->include_dir_count; i++) {
            fprintf(file, " %s", config->include_dirs[i]);
        }
    }
    else {
        fprintf(file, " include");
    }

    fprintf(file, ")\n\n");
}

// Writes target_link_directories and target_link_libraries for manual libs
static void write_libs(FILE* file, project_config_t* config) {
    if (config->lib_dir_count > 0) {
        fprintf(file, "target_link_directories(%s PRIVATE", config->name);
        for (int i = 0; i < config->lib_dir_count; i++) {
            fprintf(file, " ${CMAKE_SOURCE_DIR}/%s", config->lib_dirs[i]);
        }
        fprintf(file, ")\n\n");
    }

    if (config->lib_count > 0) {
        fprintf(file, "target_link_libraries(%s PRIVATE", config->name);
        for (int i = 0; i < config->lib_count; i++) {
            fprintf(file, " %s", config->libs[i]);
        }
        fprintf(file, ")\n\n");
    }
}

// Writes cmake for a local path dependency (must be a Craft project)
static int write_path_dependency(FILE* file, const char* project_path, project_config_t* config, dependency_t* dep) {
    char dep_root[1024];
    snprintf(dep_root, sizeof(dep_root), "%s/%s", project_path, dep->value);

    project_config_t dep_config;
    if (load_project_config(&dep_config, dep_root) != 0) {
        fprintf(stderr, "Error: could not load craft.toml for dependency '%s'\n", dep->name);
        return -1;
    }

    fprintf(file, "# %s\n", dep->name);
    fprintf(file, "add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/%s ${CMAKE_BINARY_DIR}/%s)\n", dep->value, dep->name);
    fprintf(file, "target_link_libraries(%s PRIVATE %s)\n", config->name, dep->name);

    if (dep_config.include_dir_count > 0) {
        fprintf(file, "target_include_directories(%s PRIVATE", config->name);
        for (int j = 0; j < dep_config.include_dir_count; j++) {
            fprintf(file, " %s/%s", dep->value, dep_config.include_dirs[j]);
        }
        fprintf(file, ")\n");
    }
    else {
        fprintf(file, "target_include_directories(%s PRIVATE %s/include)\n", config->name, dep->value);
    }

    fprintf(file, "\n");
    return 0;
}

// Writes cmake for a git dependency
// If it is a Craft project use add_subdirectory
// If it has a CMakeLists.txt use add_subdirectory with user provided links
// Otherwise warn the user to configure it manually
static int write_git_dependency(FILE* file, const char* project_path, project_config_t* config, dependency_t* dep) {
    char dep_root[1024];
    snprintf(dep_root, sizeof(dep_root), "%s/.craft/deps/%s", project_path, dep->name);

    char dep_cmake[1024];
    snprintf(dep_cmake, sizeof(dep_cmake), "%s/CMakeLists.txt", dep_root);

    fprintf(file, "# %s\n", dep->name);

    // Best case, it's a Craft project, we know everything
    if (is_craft_project(dep_root)) {
        project_config_t dep_config;
        if (load_project_config(&dep_config, dep_root) != 0) {
            fprintf(stderr, "Error: could not load craft.toml for dependency '%s'\n", dep->name);
            return -1;
        }

        fprintf(file, "add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/.craft/deps/%s ${CMAKE_BINARY_DIR}/%s)\n", dep->name, dep->name);
        fprintf(file, "target_link_libraries(%s PRIVATE %s)\n", config->name, dep->name);

        if (dep_config.include_dir_count > 0) {
            fprintf(file, "target_include_directories(%s PRIVATE", config->name);
            for (int j = 0; j < dep_config.include_dir_count; j++) {
                fprintf(file, " .craft/deps/%s/%s", dep->name, dep_config.include_dirs[j]);
            }
            fprintf(file, ")\n");
        }
        else {
            fprintf(file, "target_include_directories(%s PRIVATE .craft/deps/%s/include)\n", config->name, dep->name);
        }
    }

    // Has CMakeLists.txt but not a Craft project
    // Use add_subdirectory with user provided links
    else if (file_exists(dep_cmake)) {
        fprintf(file, "add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/.craft/deps/%s ${CMAKE_BINARY_DIR}/%s)\n", dep->name, dep->name);

        if (dep->links_count > 0) {
            fprintf(file, "target_link_libraries(%s PRIVATE", config->name);
            for (int j = 0; j < dep->links_count; j++) {
                fprintf(file, " %s", dep->links[j]);
            }
            fprintf(file, ")\n");
        }
        else {
            fprintf(stderr, "Warning: dependency '%s' has no link targets specified\n", dep->name);
            fprintf(stderr, "         Add --links when running craft add, or configure manually in craft.toml\n");
        }

        fprintf(file, "target_include_directories(%s PRIVATE .craft/deps/%s/include)\n", config->name, dep->name);
    }

    // No CMakeLists.txt - warn the user
    else {
        fprintf(stderr, "Warning: dependency '%s' does not appear to use CMake\n", dep->name);
        fprintf(stderr, "         Configure it manually in CMakeLists.extra.cmake\n");
    }

    fprintf(file, "\n");
    return 0;
}

// Writes the dependencies section with all dependencies using the previous helper functions
static int write_dependencies(FILE* file, const char* project_path, project_config_t* config) {

    // Only write if there are dependencies present
    if (config->dependencies_count > 0) {
        fprintf(file, "# Dependencies\n\n");
        for (int i = 0; i < config->dependencies_count; i++) {
            dependency_t* dep = &config->dependencies[i];

            // Local path dependency to another craft project
            if (dep->type == DEP_PATH) {
                if (write_path_dependency(file, project_path, config, dep) != 0) {
                    fclose(file);
                    return -1;
                }
            }

            // Github external dependency
            else if (dep->type == DEP_GIT) {
                if (write_git_dependency(file, project_path, config, dep) != 0) {
                    fclose(file);
                    return -1;
                }
            }
        }
    }

    return 0;
}

// Writes the escape hatch include
static void write_escape_hatch(FILE* file) {
    fprintf(file, "if(EXISTS ${CMAKE_SOURCE_DIR}/CMakeLists.extra.cmake)\n");
    fprintf(file, "    include(${CMAKE_SOURCE_DIR}/CMakeLists.extra.cmake)\n");
    fprintf(file, "endif()\n");
}

int generate_cmake(const char* project_path, project_config_t* config) {
    char cmake_path[1024];
    snprintf(cmake_path, sizeof(cmake_path), "%s/CMakeLists.txt", project_path);

    FILE* file = fopen(cmake_path, "w");
    if (!file) {
        fprintf(stderr, "Error: Failed to create CMakeLists.txt\n");
        return -1;
    }

    write_header(file, config);
    write_sources(file, config);
    write_target(file, config);
    write_includes(file, config);
    write_libs(file, config);
    write_dependencies(file, project_path, config);

    write_escape_hatch(file);
    fclose(file);
    return 0;
}