#include "project.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <sys/stat.h>

#include "utils.h"
#include "config.h"
#include "cmake.h"
#include "platform.h"

int create_project_from_template(const char* path, const char* template, const char* lang, int use_git) {
    char template_dir[PATH_SIZE];

    // Check for template in custom templates
    get_template_directory(template_dir, sizeof(template_dir), "custom", lang, template);
    if (!dir_exists(template_dir)) {
        // Check for template in builtin templates
        get_template_directory(template_dir, sizeof(template_dir), "builtin", lang, template);
        if (!dir_exists(template_dir)) {
            // Template not found
            fprintf(stderr, "Error: Template '%s' not found for language '%s'\n", template, lang);
            return -1;
        }
    }

    // Copy template over to project directory
    copy_dir_contents(template_dir, path, NULL, 0);

    // Load the project config from the craft.toml and set the project name and version
    project_config_t project_config;
    if (load_project_config(&project_config, path) != 0) {
        return -1;
    }

    char project_name[32];
    get_dir_name(project_name, sizeof(project_name), path);
    snprintf(project_config.name, sizeof(project_config.name), "%s", project_name);
    snprintf(project_config.version, sizeof(project_config.version), "0.1.0");

    // Make sure project configs from the template are valid
    if (validate_project_config(&project_config) != 0) {
        return -1;
    }

    // Generate a new craft.toml with name and version
    if (generate_craft_toml(path, &project_config) != 0) {
        return -1;
    }

    // Generate starting CMakeLists.txt based on configs
    if (generate_cmake(path, &project_config) != 0) {
        return -1;
    }

    // Generate .craft directory with deps directory
    char craft_directory[PATH_SIZE];
    char craft_deps_directory[PATH_SIZE];
    snprintf(craft_directory, sizeof(craft_directory), "%s/.craft", path);
    snprintf(craft_deps_directory, sizeof(craft_deps_directory), "%s/deps", craft_directory);

    mkdir(craft_directory, 0755);
    mkdir(craft_deps_directory, 0755);

    // Init git unless specified not to
    if (use_git) return init_git(path);

    return 0;
}

// Gets the full path to the new project directory from the cwd and relative path
int get_project_path(char* buffer, size_t buffer_size, const char* cwd, const char* rel_path)
{
    // Check if directory at path already exists
    char full_path[PATH_SIZE];
    snprintf(full_path, sizeof(full_path), "%s/%s", cwd, rel_path);

    if (dir_exists(full_path))
    {
        fprintf(stderr, "Error: Directory with that name already exists\n");
        return -1;
    }

    snprintf(buffer, buffer_size, "%s", full_path);
    return 0;
}

// Generates a gitignore or appends to existing to ignore craft generated files
static int generate_gitignore(const char* project_root) {
    char gitignore_path[PATH_SIZE];
    snprintf(gitignore_path, sizeof(gitignore_path), "%s/.gitignore", project_root);

    // Check if already exists and should append
    int already_exists = file_exists(gitignore_path);

    // Open gitignore
    FILE* file = NULL;
    if (already_exists) {
        file = fopen(gitignore_path, "a");
    }
    else {
        file = fopen(gitignore_path, "w");
    }

    if (!file) {
        fprintf(stderr, "Error: Failed to write gitignore\n");
        return -1;
    }

    // Write to file
    fprintf(file, "# Generated by Craft\n");
    fprintf(file, ".craft/\n");
    fprintf(file, "build/\n");
    fprintf(file, "CMakeLists.txt\n");
    fclose(file);

    return 0;
}

int init_git(const char* project_root) {

    // Check if .git already exists
    char git_dir[PATH_SIZE];
    snprintf(git_dir, sizeof(git_dir), "%s/.git", project_root);

    // Run git init in project directory if doesnt already exist
    if (!dir_exists(git_dir)) {
        char cmd[COMMAND_SIZE];
        snprintf(cmd, sizeof(cmd), "git init \"%s\" > %s 2>&1", project_root, DEVNULL);
        system(cmd);
    }

    // Write or append to gitignore
    return generate_gitignore(project_root);
}

int handle_project(const command_t* command_data) {
    // Retrive path of current working directory where craft is being called
    char cwd[PATH_SIZE];
    if (get_cwd(cwd, sizeof(cwd)) == NULL)
    {
        fprintf(stderr, "Error: Failed to get current working directory\n");
        return -1;
    }
    
    // Load global configs and set defaults
    craft_config_t global_config;
    load_global_config(&global_config);

    const char* rel_project_path = command_data->args[0];
    const char* language = global_config.language;
    const char* template = global_config.template;
    int use_git = 1;

    // Override defaults with option arguments
    for (int i = 0; i < command_data->option_count; i++) {
        if (strcmp(command_data->options[i].name, "template") == 0) {
            template = command_data->options[i].arg;
        }
        if (strcmp(command_data->options[i].name, "lang") == 0) {
            language = command_data->options[i].arg;
        }
        if (strcmp(command_data->options[i].name, "no-git") == 0) {
            use_git = 0;
        }
    }

    // Get path to project
    char project_path[PATH_SIZE];
    if (get_project_path(project_path, sizeof(project_path), cwd, rel_project_path) != 0) { 
        return -1;
    }

    // Create new directory and create the project
    mkdir(project_path, 0755);
    if (create_project_from_template(project_path, template, language, use_git) != 0) {
        return -1;
    }

    // Print success mesage
    char project_name[32];
    get_dir_name(project_name, sizeof(project_name), project_path);
    fprintf(stdout, "Created Craft project '%s'\n\n", project_name);

    fprintf(stdout, "Tip: Run 'craft build' to build your new project\n");
    return 0;
}